### ISSUE TITLE
Loading circle animation not showing

### ISSUE THREAD

**Issue by jloracudris** [PygmySlowLoris/vue-full-loading#11]
Hey guys 

i have a problem that i can also see in your live demo, the circle of loading is not showing for some reason, 
the weird thing about it is that in my local machine i can see it but when i upload it to the live server i cant see any circle animation just the label, just as your live demo

**Comment by Edujugon** [comment]
Hi @jloracudris ,
Thanks for reporting it, I just realised that is also happening in our live demo..

I'm not sure when I'll have some free time to check that. If in the meantime you find out the problem, feel free to submit a PR or comment in here.

**Comment by AyushG3112** [comment]
@Edujugon I think I figured out the issue, PR coming in later today if the fix works.

**Comment by AyushG3112** [comment]
@Edujugon fix up. Let me know if any changes are needed.
