### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by sudoak** [PygmySlowLoris/vue-full-loading#12]
Copied the code from NPM on local machine. Nothing shows up.

**Comment by Edujugon** [comment]
Hi @sudoak ,
Could you share the steps you took? are you getting any error message?

**Comment by sudoak** [comment]
![screen shot 2018-04-10 at 5 44 27 pm](https://user-images.githubusercontent.com/25544768/38556315-dbd4f092-3ce6-11e8-9f21-e5434476fc15.png)

**Comment by Edujugon** [comment]
Any error in console?

**Comment by sudoak** [comment]
No Error in console. Tried in two separate projects, didn't work. 
![screen shot 2018-04-10 at 6 05 50 pm](https://user-images.githubusercontent.com/25544768/38557198-d4947124-3ce9-11e8-8bca-d6abde328d75.png)

**Comment by Edujugon** [comment]
I assume you've installed the latest package version.

I'll test it as soon as I get some free time and I'll get back to you with an update.

**Comment by Edujugon** [comment]
Hi @sudoak ,

I've just remembered that we made this package not expecting that it would start showing the overlay.

So the idea was, the show prop start as false and it is set to true when a specific action occurs. 

Just to proof this is working, just try the following:
Set `show` prop to `false`
and add this just below data function:
```js
mounted() {
   setTimeout(() => this.show = true,2000)
}
```

With the above additions, you will see that after a few seconds the overlay is shown..

Hope this helps.

**Comment by sudoak** [comment]
This works
setTimeout(() => this.show= true,2000)

This Doesn't
setTimeout(function(){ this.show = true}, 2000);

**Comment by Edujugon** [comment]
The above code snippet doesn't work because the funtion scope, nothing about this package..

So my example worked, right?
Should I close this ticket then?

**Comment by sudoak** [comment]
👍🏻
