### ISSUE TITLE
Change position of spinner

### ISSUE THREAD

**Issue by ultrasamad** [PygmySlowLoris/vue-full-loading#6]
Hello, Is it possible to change the position of the spinner especially on mobile devices where the spinner is out of view.

**Comment by Edujugon** [comment]
Hi @ultrasamad ,
I've just released a new version which supports what you are looking for.
Have a look at [the new slot feature](https://github.com/PygmySlowLoris/vue-full-loading#slots).

So now you can easily add your own content with its styles for the spinner.

I'm also thinking to make the default spinner container class dynamic so you can just change that class with its style without having to use the slots..

Anyway, let me know if that worked for you.

**Comment by Edujugon** [comment]
Hi @ultrasamad ,
As mentioned in my previous message, We've released a new version where now you can set your own loader wrapper class.
The new prop is `loader-class`

Hope any of those approaches helps you to solve your issue.

**Comment by ultrasamad** [comment]
@Edujugon Ok cool. I Will take a look at it and see if that will solve my issue. Thanks!

**Comment by Edujugon** [comment]
I'm closing this since there is no update from the creator.

Feel free to reopen it if needed
