### ISSUE TITLE
Overlay-class is not configurable

### ISSUE THREAD

**Issue by SvenSchoene** [PygmySlowLoris/vue-full-loading#8]
I am generally pretty happy with this library, thanks for sharing!  

Weirdly enough, however, there is no way to overwrite the class for the overlay. It's always `white-overlay` if the `overlay`-prop is set to `true`.  
This is an easy fix, but I would greatly appreciate it.  

Possible use cases:
- In my application there's a lot of `z-index`-spamming already and I need to increase the `z-index` of `.white-overlay`.
- Maybe one doesn't want to have a white overlay, but a black one?

**Comment by Edujugon** [comment]
Hi @SvenSchoene ,

Good idea :)
I've just realised a new version where you can set the overlay as prop. (`overlay-class`)

Give it a try and let me know.
Regards

**Comment by SvenSchoene** [comment]
@Edujugon Peeeeerfect! Thanks alot!  👍

**Comment by Edujugon** [comment]
My pleasure, glad it helped :)
