### ISSUE TITLE
Custom loader-class not working

### ISSUE THREAD

**Issue by sergiochtf** [PygmySlowLoris/vue-full-loading#9]
When I replace the class in my code, the class name is replace but the properties of the new class is not showed. I had to put my new class in the global CSS file.

**Comment by Edujugon** [comment]
You can define that class either globally as you did, or in the parent component from where you are calling the vue-full-loading component or any other where the style is not scoped..

Do you see this as in issue? what would be your approach?

**Comment by sergiochtf** [comment]
It's ok, I'm close the issue. I defined the class globally.
